--- 
name: framework_spec
bbver: 4.6
sdk: /Users/brian/work/rhodes
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
iphone: 
  sdk: iphonesimulator3.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug
